### ISSUE TITLE
File fails verification leading to removal from filesystem

### ISSUE THREAD

**Issue by dullbouy** [rsvihladremio/ssdownloader#15]
Download leads to some files failing verification post download at which point they are removed from the filesystem

```
ssdownloader v0.4.0-68ec264-darwin-amd64

2022/07/19 10:01:08 downloading /path/to/tickets/118437/20220718T131342_V47T-Y6RW/server.log
2022/07/19 10:01:08 making dir /path/to/tickets/118437/20220719T082412_S77C-3ZGT
2022/07/19 10:01:08 downloading /path/to/tickets/118437/20220719T082412_S77C-3ZGT/server.log
2022/07/19 10:01:08 downloading /path/to/tickets/118437/20220719T072022_Z3NJ-22ER/server.log
2022/07/19 10:01:10 file '/path/to/tickets/118437/20220718T131342_V47T-Y6RW/server.log is complete and is 148.99 kb on disk
2022/07/19 10:01:10 ERROR: file /path/to/tickets/118437/20220718T131342_V47T-Y6RW/server.log failed verification, removing
2022/07/19 10:01:11 file '/path/to/tickets/118437/20220719T082412_S77C-3ZGT/server.log is complete and is 2.05 mb on disk
2022/07/19 10:01:11 ERROR: file /path/to/tickets/118437/20220719T082412_S77C-3ZGT/server.log failed verification, removing
2022/07/19 10:01:12 file '/path/to/tickets/118437/20220719T072022_Z3NJ-22ER/server.log is complete and is 1.45 mb on disk
2022/07/19 10:01:12 ERROR: file /path/to/tickets/118437/20220719T072022_Z3NJ-22ER/server.log failed verification, removing
```

If I download manually from sendsafely ( not via the ssdownloader ) and place in the associated directory created by ssdownloader the files look like so:

```
./20220718T131342_V47T-Y6RW:
total 312
-rw-------  1 myname  staff     154 19 Jul 10:39 comment.txt
-rw-r--r--@ 1 myname  staff  152562 19 Jul 10:42 server.log

./20220719T072022_Z3NJ-22ER:
total 2976
-rw-------  1 myname  staff      154 19 Jul 10:39 comment.txt
-rw-r--r--@ 1 myname  staff  1515772 19 Jul 10:42 server.log

./20220719T082412_S77C-3ZGT:
total 4216
-rw-------  1 myname  staff      154 19 Jul 10:39 comment.txt
-rw-r--r--@ 1 myname  staff  2151714 19 Jul 10:42 server.log
```

Incidentally, if after the above error, you download the files manually and place them in the expected download directory any further attempt to download using the ssdownloader will remove them again.

**Comment by rsvihladremio** [comment]
Looking at this more closely SendSafely is reporting back a number that does not match files downloaded through their UI

file from sendsafely.com

```sh
 ls -la ~/Downloads/server.log 
-rw-r--r--@ 1 ryan.svihla  staff  2151714 Jul 19 12:48 
```

file size of file downloaded by send safely downloader

```sh
2022/07/19 12:50:57 DEBUG: file comparison is 2151714 current
```

you will note this is the same as the one from the UI, and a diff shows the files are identical, however when logging the output of the API we see for only these handful of files it is wrong

```sh
 "fileName": "server.log",                                                                                                                                             
=                       "fileSize": "2151942",
```

I have decided to punt on this and just warn when this happens by default for this issue, and I have created issues #16 and 
#17 to deal with this more strategically and give the user more control.

In the short term I will just log invalidated files in all caps, and skip the redownload step, eventually adding it as an option back once the above tickets are done
